version: 2.1

ruby-image: &ruby-image cimg/ruby:<<parameters.ruby-version>>
env-vars: &env-vars
  RAILS_ENV: test
  NODE_ENV: test
  BUNDLE_PATH: vendor/bundle

orbs:
  browser-tools: circleci/browser-tools@1.1.3

executors:
  main-executor:
    parameters:
      ruby-version:
        description: "Ruby version"
        default: "3.2"
        type: string
    docker:
      - image: *ruby-image
        environment: *env-vars

commands:
  setup:
    description: checkout code, restore cache, install dependencies, save cache
    steps:
      - checkout
      - browser-tools/install-chrome
      - restore_cache:
          keys:
          - bundler-dependencies-{{ checksum "Gemfile.lock" }}
          - bundler-dependencies-
      - run:
          name: Install apt and vips buildpack dependencies
          command: |
            cd spec/dummy/
            xargs -a Aptfile sudo apt-get install
            sudo apt-get install libvips
            sudo apt-get install file
      - run:
          name: Install bundle dependencies
          command: |
            BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")
            gem install bundler:$BUNDLER_VERSION
            bundle _$(echo $BUNDLER_VERSION)_ install
      - save_cache:
          key: bundler-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Setup database
          command: (cd spec/dummy && bundle exec rake db:setup)
      - run:
          name: Install node and yarn
          command: |
            curl -sL https://deb.nodesource.com/setup_$(cat .node-version).x | sudo -E bash -
            sudo apt-get install -y nodejs
            curl -o- -sL https://yarnpkg.com/install.sh | bash
            sudo ln -s $HOME/.yarn/bin/yarn /usr/local/bin/yarn
      - run:
          name: Prepare Assets
          command: |
            bundle exec rake prepare_assets
            (cd spec/dummy && bundle exec rake webpacker:compile)

jobs:
  lint:
    executor: main-executor
    steps:
      - setup
      - run:
          name: Install reviewdog
          command: |
            curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ./bin
      - run:
          name: Get files to lint
          command: git diff origin/master --name-only --diff-filter=d > tmp/files_to_lint
      - run:
          name: Run rubocop
          shell: /bin/bash
          command: |
            cat tmp/files_to_lint | grep -E '.+\.(rb)$' | xargs bundle exec rubocop --force-exclusion \
            | ./bin/reviewdog -reporter=github-pr-review -f=rubocop
  test:
    parameters:
      ruby-version:
        description: "Ruby version"
        default: "2.7"
        type: string
    executor:
      name: main-executor
      ruby-version: <<parameters.ruby-version>>
    steps:
      - setup
      - run:
          name: Run Utils Tests
          command: |
            RSPEC_JUNIT_ARGS="-r rspec_junit_formatter -f RspecJunitFormatter -o test_results/utils-rspec.xml"
            RSPEC_FORMAT_ARGS="-f progress --no-color -p 10"
            bundle exec rspec ./spec/lib $RSPEC_FORMAT_ARGS $RSPEC_JUNIT_ARGS
      - run:
          name: Run Tests
          command: |
            RSPEC_JUNIT_ARGS="-r rspec_junit_formatter -f RspecJunitFormatter -o test_results/webpack-rspec.xml"
            RSPEC_FORMAT_ARGS="-f progress --no-color -p 10"
            bundle exec rspec ./spec/features $RSPEC_FORMAT_ARGS $RSPEC_JUNIT_ARGS
      - store_test_results:
          path: test_results

  deploy:
    executor: main-executor
    steps:
      - setup
      - run:
          name: Setup rubygems
          command: bash .circleci/setup-rubygems.sh
      - run:
          name: Publish to rubygems
          command: |
            gem build activeadmin_addons.gemspec
            version_tag=$(git describe --tags)
            gem push activeadmin_addons-${version_tag#v}.gem
      - run:
          name: Publish to npm
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  version: 2
  test_and_lint:
    jobs:
      - lint:
          context: org-global
      - test:
          matrix:
            parameters:
              ruby-version: ["3.0", "3.1", "3.2"]
      - deploy:
          context: org-global
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
